---
title: "Homework #1: Moneyball New Data Exploration"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
    self_contained: no
editor_options: 
  chunk_output_type: console
bibliography: references.bib
---

```{r setup, include=FALSE}
library(tidyverse)
library(reshape2)
library(kableExtra)
library(Matrix)
library(MASS)
library(mice)
library(Hmisc)
library(corrplot)
library(performance)
library(naniar)
library(psych)
library(GGally)
library(campfin)
library(caret)


library(skimr)
library(summarytools)
library(explore)
library(GGally)
library(corrplot)



knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```





## 1. DATA EXPLORATION


https://www.seanlahman.com/baseball-archive/statistics/




```{r initialization, include=FALSE}

trainDf <- read.csv("https://raw.githubusercontent.com/cliftonleesps/data621_group1/main/hw1/moneyball-training-data.csv")
evalDf <- read.csv("https://raw.githubusercontent.com/cliftonleesps/data621_group1/main/hw1/moneyball-evaluation-data.csv")

```



```{r}

teamDF <- evalDf <- read.csv("https://raw.githubusercontent.com/cliftonleesps/data621_group1/main/hw1/Teams.csv")

teamDF <- teamDF %>% dplyr::select('yearID','lgID','teamID','franchID','divID','Rank','G','W','L',
                         'R','AB','H','X2B','X3B','HR','BB','SO','SB','CS','HBP','SF','RA','ER','ERA',
                         'CG','SHO','SV','IPouts','HA','HRA','BBA','SOA','E','DP','FP')




# normalize data 162 games
teamDF$gFactor <-  162 / (teamDF$W + teamDF$L)

teamDF$TARGET_WINS <-  teamDF$gFactor * teamDF$W
teamDF$TEAM_BATTING_H <- teamDF$gFactor * teamDF$H
teamDF$TEAM_BATTING_2B  <- teamDF$gFactor * teamDF$X2B
teamDF$TEAM_BATTING_3B  <- teamDF$gFactor * teamDF$X3B
teamDF$TEAM_BATTING_HR  <- teamDF$gFactor * teamDF$HR
teamDF$TEAM_BATTING_BB  <- teamDF$gFactor * teamDF$BB
teamDF$TEAM_BATTING_SO  <- teamDF$gFactor * teamDF$SO
teamDF$TEAM_BASERUN_SB  <- teamDF$gFactor * teamDF$SB
teamDF$TEAM_BASERUN_CS  <- teamDF$gFactor * teamDF$CS
teamDF$TEAM_BATTING_HBP <- teamDF$gFactor * teamDF$HBP
teamDF$TEAM_PITCHING_H  <- teamDF$gFactor * teamDF$HA
teamDF$TEAM_PITCHING_HR <- teamDF$gFactor * teamDF$HRA
teamDF$TEAM_PITCHING_BB <- teamDF$gFactor * teamDF$BBA
teamDF$TEAM_PITCHING_SO <- teamDF$gFactor * teamDF$SOA
teamDF$TEAM_FIELDING_E  <- teamDF$gFactor * teamDF$E
teamDF$TEAM_FIELDING_DP <- teamDF$gFactor * teamDF$DP 


# Pythagorean winning percentage
#  (runs scored ^ 2) / [(runs scored ^ 2) + (runs allowed ^ 2)]
teamDF$pythPercent <- (teamDF$R^2) / ((teamDF$R^2) + (teamDF$RA^2))


teamAdjDF <- teamDF %>% dplyr::select("TARGET_WINS","TEAM_BATTING_H","TEAM_BATTING_2B","TEAM_BATTING_3B","TEAM_BATTING_HR",
                "TEAM_BATTING_BB","TEAM_BATTING_SO","TEAM_BASERUN_SB","TEAM_BASERUN_CS",
                "TEAM_BATTING_HBP","TEAM_PITCHING_H","TEAM_PITCHING_HR","TEAM_PITCHING_BB",
                "TEAM_PITCHING_SO","TEAM_FIELDING_E","TEAM_FIELDING_DP")

```




#### 1.1 Summary Statistics




```{r}

st_options(
  dfSummary.custom.2 = 
    expression(
      paste(
        "Q1 - Q3 :",
        round(
          quantile(column_data, probs = .25, type = 2, 
                   names = FALSE, na.rm = TRUE), digits = 1
        ), " - ",
        round(
          quantile(column_data, probs = .75, type = 2, 
                   names = FALSE, na.rm = TRUE), digits = 1
        )
      )
    )
)


print(
  dfSummary(trainDf, 
            varnumbers   = TRUE,
            na.col       = FALSE,
            style        = "grid",
            plain.ascii  = FALSE,
            freq.silent  = TRUE,
            headings     = TRUE,
            graph.magnif = .8,
            tmp.img.dir  = "/tmp"),
  method = "viewer"
)

```



```{r}

print(
  dfSummary(teamDF, 
            varnumbers   = TRUE,
            na.col       = FALSE,
            style        = "grid",
            plain.ascii  = FALSE,
            freq.silent  = TRUE,
            headings     = TRUE,
            graph.magnif = .8,
            tmp.img.dir  = "/tmp"),
  method = "viewer"
)

```




#### 1.2 Distribution and Box Plots

```{r density_boxplot, echo=FALSE, warning=FALSE, message=FALSE, fig.height=8, fig.width=10}

m_df <- teamAdjDF %>% melt() 

m_df %>% ggplot(aes(x= value)) + 
    geom_density(color='#023020', fill='gray') + facet_wrap(~variable, scales = 'free',  ncol = 4) + theme_bw()


m_df %>% ggplot(aes(x = value)) +
  geom_boxplot(outlier.color = 'red', outlier.shape = 1) +
  facet_wrap(vars(variable),scales = "free", ncol = 4)

```


```{r wins_features, echo=FALSE, fig.height=8, fig.width=10}

featurePlot(teamAdjDF[,2:ncol(teamAdjDF)], teamAdjDF[,1], plot = "scatter", type = c("p", "smooth"), span = 1)

```

#### 1.3 Correlation Matrix


```{r correlation_matrix, echo=FALSE}
rcore <- rcorr(as.matrix(teamAdjDF %>% dplyr::select(where(is.numeric))))
coeff <- rcore$r
corrplot(coeff, tl.cex = .7 , method = 'number')
```



```{r corr_numbers, echo=FALSE}
tst <- teamAdjDF
tst <- tst[,-1 ]

kable(cor(drop_na(tst))[,1], "html", escape = F, col.names = c('Coefficient')) %>%
  kable_styling("striped", full_width = F) %>%
  column_spec(1, bold = T)


```



## 2. DATA PREPARATION




### 3. BUILD MODELS

 


```{r}


lmA1 <- lm(TARGET_WINS ~ ., data = teamAdjDF)
lmA1Sum <- summary(lmA1)
lmA1Sum

```




```{r}

lmA1.step <- stepAIC(lmA1, trace = FALSE)
lmA1Sum.step <- summary(lmA1.step)
lmA1Sum.step

```






### Pythagorean winning percentage

```{r}

lm2 <- lm(TARGET_WINS ~ pythPercent, data = teamDF)
summary(lm2)

```



## 4. SELECT MODELS








## Conclusion














